In [19]:
from scipy import stats
import numpy as np

### O que faz

rvs significa algo como random variates.

Ele serve para simular observações que seguem aquela distribuição.

In [20]:
stats.norm.rvs(size=5)

array([ 0.24146506,  0.08614516,  1.67701301,  0.53709046, -1.31219854])

In [21]:
stats.norm.rvs(loc=70, scale=10, size=5)

array([54.01886016, 84.37380479, 53.25330954, 85.61147198, 66.13056399])

In [22]:
notas = stats.norm.rvs(loc=70, scale=10, size=1000)
print(notas[:10])

[55.94015077 74.84960432 64.25980594 81.03783368 62.76329045 81.83924196
 60.18164375 77.78851435 73.06449966 79.27982085]


In [23]:
print(np.mean(notas))

69.9727307972493


In [24]:
print(np.std(notas))

9.928576847194156


In [25]:
print(np.max(notas))

98.74302062848423


In [26]:
print(np.min(notas))

37.24346212748308


### Simulando número de chamadas com Poisson

In [27]:
chamadas = stats.poisson.rvs(mu=4, size=200)
print(chamadas)

[ 1  8  3  2  7  4  8  8  3  5  5  4  5  4  4  4  1  3  5  2  4  6  4  7
  3  4  3  2  3  4  3  4  5  5  5  4  7  7  4  2  3  2  3  4  0  7  4  6
  1  5  6  4  1  6  3  1  3  4  5  4  0  4  3  9  6  5  4  6  2  4  3  6
  4  2  1  2  8  5  1  3  5  1  3  1  3  3  3  5  4  2  4  5  6  2  5  3
  6  4  2  3  9  3  3  3  5  2  2  2  9  6  5  6  4  1  2  3  1  7  2  5
  6  2  1  2  2  3  0  4  5  1  4  7  2  3  1  3  8  4  3  3  4  2  4  3
  2  4  1  6  2  3  5  2 11  2  5  3  5  1  5  4  5  5  5  3  3  5  4  9
  3  3  3  6  1  3  6  7  5  7  8  1  3  4  1  3  6  4  2  7  4  2  4  4
  5  4  3  3  1  2  1  0]


In [28]:
rng = np.random.default_rng(42)
amostra = stats.norm.rvs(loc=70, scale=10, size=5, random_state=rng)
print(amostra)

[73.0471708  59.60015894 77.50451196 79.40564716 50.48964811]


Usar pdf() para:

- entender o formato da distribuição
- comparar onde a curva é mais alta
- construir gráficos
- analisar a densidade em certos pontos